language: node_js
node_js:
  - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "10"
  - "8"
  - "6.10"

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

script:
   - node --version
   - npm --version
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
